language: node_js

install:
  - npm install
  -
before_install:
  - npm install -g npm@latest
  - npm --version

jobs:
  include:
    - stage: "Tests"
      name: "Tests"
      script:
        - npm test
